### ISSUE TITLE
Use double underscore inv ENV config override

### ISSUE THREAD

**Issue by zarbis** [vfarcic/docker-flow-monitor#17]
There is ambiguity in current ENV naming rules such as: `GLOBAL_SCRAPE_INTERVAL=10s`
Can be treated as:
```
global:
  scrape_interval: 10s
```
as well as:
```
global:
  scrape:
    interval: 10s
```

To avoid ambiguity and complexity of parsing next nesting level should be indicated with double underscore where single underscore should be treated literally.
With such rule there is no ambiguity in `GLOBAL__SCRAPE_INTERVAL=10s` or `GLOBAL__EXTERNAL_LABELS__LABEL_TYPE=production`.

**Comment by vfarcic** [comment]
Wanna give it a try with a PR?

**Comment by thomasjpfan** [comment]
I want to flesh this idea out before implementing it. 

```yaml
remote_write:
  - url: http://remote1/push
    write_relabel_configs:
    - regex: expensive.*
      action: drop
  - url: http://remote2/push
```

Should the ENV config be the following?
```
REMOTE_WRITE__URL_1=http://remote1/push
REMOTE_WRITE__WRITE_RELABEL_CONFIGS_1__REGEX_1=expensive.*
REMOTE_WRITE__WRITE_RELABEL_CONFIGS_1__ACTION_1=drop
REMOTE_WRITE__URL_2=http://remote2/push
```
