### ISSUE TITLE
Additional manual scrape configs

### ISSUE THREAD

**Issue by corvus-ch** [vfarcic/docker-flow-monitor#4]
I have setup a swarm cluster with docker flow monitor for monitoring. All is working fine so far. No I have the use case where I have to define some scrape configs manually. 

Why do I need to write this scrape config manually? I am using blackbox_exporter for probing some external service (outside of my control) and for that I need a bunch of relabel statements.

As far as I can see, this is not supported. Since I can nighter set relabelling thought docker labels nor I can define some custom scrape configs. How should I approach this use case?

Thanks in advance for help.

**Comment by vfarcic** [comment]
PR #3 will add the feature you need. @albertogviana is working on it. It should be available soon.

**Comment by corvus-ch** [comment]
Thanks for the fast reply.

The solution in PR #3 will solve my problem only partially as it does not address my need for relabelling. Please have a look at the following Prometheus config snipped.

```
scrape_configs:
  - job_name: example
    dns_sd_configs:
      - names: ["example.com"]
        type: A
        port: 443
    metrics_path: /probe
    params:
      module: [example]
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*)
        target_label: __param_target
        replacement: https://${1}/v1/rest/resource
      - source_labels: [__address__]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
```
