### ISSUE TITLE
Problem with "Additional scrapes"

### ISSUE THREAD

**Issue by vicjeancar** [vfarcic/docker-flow-monitor#7]
there is a problem to start a container when  i try to load a secret with the configuration inside i am using this context
```
  - job_name: 'mongo-instance'
    scrape_interval: 5s
    static_configs:
      - targets: ['xxx.xxx.xx.xxx:9100']
```

in a file named "scrape_mongodb"

**Comment by vfarcic** [comment]
Please take a look at the commands and screen outputs that follow.

```bash
git clone https://github.com/vfarcic/docker-flow-monitor.git

cd docker-flow-monitor

./scripts/dm-swarm.sh

eval $(docker-machine env swarm-1)

docker network create -d overlay monitor

docker stack deploy \
    -c stacks/docker-flow-monitor-tutorial.yml \
    monitor

echo '
  - job_name: "mongo-instance"
    scrape_interval: 5s
    static_configs:
      - targets: ["1.2.3.4:9100"]
' | docker secret create scrape_mongo -

docker service update --secret-add scrape_mongo monitor_monitor

open "http://$(docker-machine ip swarm-1):9090/config"
```

[screen output]
```
global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "mongo-instance"
    scrape_interval: 5s
    static_configs:
      - targets: ["1.2.3.4:9100"]
```

```bash
docker stack deploy \
    -c stacks/exporters-tutorial.yml \
    exporter

open "http://$(docker-machine ip swarm-1):9090/config"
```

[screen output]
```
global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "exporter_cadvisor"
    dns_sd_configs:
      - names: ["tasks.exporter_cadvisor"]
        type: A
        port: 8080
  - job_name: "exporter_node-exporter"
    dns_sd_configs:
      - names: ["tasks.exporter_node-exporter"]
        type: A
        port: 9100

  - job_name: "mongo-instance"
    scrape_interval: 5s
    static_configs:
      - targets: ["1.2.3.4:9100"]


rule_files:
  - 'alert.rules'
```

```bash
docker-machine rm -f swarm-1 swarm-2 swarm-3
```

Everything seems to be working OK. Can you please post the commands you used?

**Comment by vicjeancar** [comment]
i want to use the secrets in a docker-compose file, can you send me and example of the docker compose and the scrape file has is going to be, i mean the context, i am doing this in a aws cloudformation stack swarm, i am using the context in a file already load in my secrets in the ucp

**Comment by vfarcic** [comment]
If you already have the secret created, you need to add to you compose file something like:

```yml
...
services:

  monitor:
    ...
    secrets:
      - scrape_mongodb
      ...

secrets:
  scrape_mongodb:
    external: true
```
